name: aml2
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - defaults
dependencies:
  - numpy
  - ipykernel
  - seaborn
  - scikit-learn
  - opencv
  - requests
  - jupyter
  - ipywidgets
  - widgetsnbextension
  - dataclasses
  - tqdm
  - imagehash
  - torchmetrics
  - sympy
prefix: C:\Users\lukesaleh\anaconda3\envs\aml2
